version: "3"

services:
  exams-api-service:
    build:
      context: .
      target: development
    env_file: .env
    volumes:
      - .:/home/node
    command: /bin/sh -c "npm i && npm run start:dev"
    networks:
      - default
      - bng

  exams-db-service:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 54323:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - bng-exams-db-data:/var/lib/postgresql/data:rw
    networks:
      - default

volumes:
  bng-exams-db-data: {}
 
networks:
  default:
    driver: bridge
  bng:
    external: true
