version: '3'

services:
  exams-api-service:
    image: adxl/bng-api-exams:latest
    environment:
      STAGE: production
      DATABASE_URL: '@DATABASE_URL@'
    networks:
      - bng
    deploy:
      replicas: 3

networks:
  bng:
    external: true
