version: "3"

services:
  api:
    container_name: bng_api_exams
    image: node:18-alpine
    user: node
    working_dir: /home/node
    env_file: .env
    ports:
      - 9003:9000
    volumes:
      - .:/home/node
    command: /bin/sh -c "npm i && npm run start:dev"
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.exams.rule=PathPrefix(`/exams`)"
    networks:
      - bng

  db:
    container_name: bng_db_exams
    image: postgres:13-alpine
    ports:
      - 54323:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - bng-exams-db-data:/var/lib/postgresql/data:rw

volumes:
  bng-exams-db-data: {}
 
networks:
  bng:
    external: true
