version: "3"

services:
  api:
    container_name: bng_api_exams
    build:
      context: docker/api
      target: development
    env_file: .env
    volumes:
      - .:/home/node
    command: /bin/sh -c "npm i && npm run start:dev"
    networks:
      - default
      - bng

  db:
    container_name: bng_db_exams
    image: postgres:13-alpine
    ports:
      - 54323:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - bng-exams-db-data:/var/lib/postgresql/data:rw
    networks:
      - default

volumes:
  bng-exams-db-data: {}
 
networks:
  default:
    driver: bridge
  bng:
    external: true
