version: '3'

services:
  exams-api-service:
    image: adxl/bng-api-exams:latest
    networks:
      - bng
      - default
    deploy:
      replicas: 3

  exams-db-service:
    image: adxl/bng-db-exams:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - default
    deploy:
      replicas: 2

networks:
  default:
    driver: overlay
  bng:
    external: true

