version: '3'

services:
  api:
    image: adxl/bng-api-exams:latest
    deploy:
      replicas: 3

  db:
    image: adxl/bng-db-exams:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    deploy:
      replicas: 2
